import './globals.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { Container } from '@/components/ui';
import { cn } from '@/utils';
import { TooltipProvider } from '@/components/ui/Tooltip';
import { PositionProvider } from '@/contexts/positions';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" prefix="og: http://ogp.me/ns#">
      <body className={cn('bg-pink-500 text-primary-foreground antialiased')}>
        <PositionProvider>
          <TooltipProvider>{children}</TooltipProvider>
        </PositionProvider>
      </body>
    </html>
  );
}
